.PHONY: all
all:
	$(MAKE) -C cages/ all
	$(MAKE) -C end_sequence/ all
	$(MAKE) -C castle_hall/ all
	$(MAKE) -C gate/ all
	$(MAKE) -C gate_demo/ all

.PHONY: clean
clean:
	rm -f $(ALL_OUTPUT)
	$(MAKE) -C cages/ clean
	$(MAKE) -C end_sequence/ clean
	$(MAKE) -C castle_hall/ clean
	$(MAKE) -C gate/ clean
	$(MAKE) -C gate_demo/ clean
