# Note about file_to_pascal_string: it's another program of mine,
# you can get it from pasdoc [http://pasdoc.sourceforge.net/] sources.

castle_help_message.inc: castle_help_message.txt
	file_to_pascal_string castle_help_message.txt castle_help_message.inc
